package enums;

public enum EsquemaTratamento {
    PV_CLOROQUINA_PRIMAQUINA,
    PF_QUININA_DOXICICLINA_PRIMAQUINA,
    MISTAS_PV_PF_MEFLOQUINA_PRIMAQUINA,
    PM_CLOROQUINA,
    PV_CRIANCAS_VOMITOS,
    PF_MEFLOQUINA_PRIMAQUINA,
    PF_QUININA_7DIAS,
    PF_CRIANCAS_ARTESUNATO_RETAL,
    MISTAS_PV_PF_QUININA_3DIAS,
    PREVENCAO_RECAIDA_PV,
    MALARIA_GRAVE_COMPLICADA,
    PF_ARTEMETER_LUMERFANTRINA,
    OUTRO
}
