package enums;

public enum ModoEntradaHanseniase {
    CASO_NOVO,
    TRANSFERENCIA_MESMO_MUNICIPIO,
    TRANSFERENCIA_OUTRO_MUNICIPIO,
    TRANSFERENCIA_OUTRO_ESTADO,
    TRANSFERENCIA_OUTRO_PAIS,
    RECIDIVA,
    OUTROS_REINGRESSOS,
    IGNORADO
}
