package enums;

public enum ResultadoTesteSensibilidade {
    RESISTENTE_SOMENTE_A_ISONIAZIDA,
    RESISTENTE_SOMENTE_A_RIFAMPICINA,
    RESISTENTE_A_ISONIAZIDA_E_RIFAMPICINA,
    RESISTENTE_A_OUTRAS_DROGAS_DE_PRIMEIRA_LINHA,
    SENSIVEL,
    EM_ANDAMENTO,
    NAO_REALIZADO
}
