package enums.gerais;

public enum Escolaridade {
    ANALFABETO,
    FUNDAMENTAL_INCOMPLETO,
    FUNDAMENTAL_COMPLETO,
    MEDIO_INCOMPLETO,
    MEDIO_COMPLETO,
    SUPERIOR_INCOMPLETO,
    SUPERIOR_COMPLETO,
    POS_GRADUACAO,
    MESTRADO,
    DOUTORADO,
    NAO_INFORMADO
}
